### PR TITLE
Kaltura API Client via Composer

### PR DESCRIPTION
**Pull request by justinpage**
## Discussion

As mentioned in #1, it would be awesome to pull the Kaltura Client API form a package manager --such as Composer. To do this, I've changed the folder structure to follow best practices in relation to the [League of Extraordinary Packages](https://thephpleague.com/).

Furthermore, I've demoed this same PR with a forked example [Kaltura-Client-53](https://github.com/KLVTZ/kaltura-client53) that is then linked with [packagist](https://packagist.org/packages/klvtz/kaltura-client53). 

By doing so, users can pull in this client dependency via `"klvtz/kaltura-client53": "dev-master"`. In addition, I've auto-loaded this under PSR-4 standard.

Here's a quick example for others to reference:

``` php
# Kaltura Client API
use Kaltura\Client\Configuration as KalturaConfiguration;
use Kaltura\Client\Client as KalturaClient;
use Kaltura\Client\Enum\SessionType as KalturaSessionType;
use Kaltura\Client\Type\MediaEntryFilter as KalturaMediaEntryFilter;
use Kaltura\Client\Type\FilterPager as KalturaFilterPager;
use Kaltura\Client\ApiException;
use Kaltura\Client\ClientException;

class RecoilController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $config = new KalturaConfiguration(env('PARTNER_ID'));
        $client = new KalturaClient($config);
        $ks = $client->generateSession(env('ADMIN_SECRET'), env('USER_ID'), 
            KalturaSessionType::ADMIN, $config->getPartnerId());

        $client->setKs($ks);
        $filter = new KalturaMediaEntryFilter;
        $pager = new KalturaFilterPager;

        $filter->categoriesMatchAnd = 'Recoil';
        $pager->pageSize = 500;
        $pager->pageIndex = 1;
        $result = $client->media->listAction($filter, $pager);
        var_dump($result); die();

    }
}
```
## To-do

If you do decide to go this route, which I highly suggest, we will need to re-do the tests for travis to pass.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @KLVTZ,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by kaltura-hooks** [comment]
Hi @KLVTZ,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by zoharbabin** [comment]
@KLVTZ , as noted in #1 - Such patches should be made against the proper generator scripts, not the generatED client.
Thanks!

**Comment by zoharbabin** [comment]
@KLVTZ - Also note that we have a branch open for composer related updates. You're welcome to join in there - https://github.com/kaltura/server/tree/Jupiter-10.5.0-PHP53-Client-Composer-Support

Composer json -
https://github.com/kaltura/server/commit/69c4ea443b694a1da83b847b71645d6edb188565

**Comment by justinpage** [comment]
@zoharbabin thanks for taking the time to explain my mishaps. I'll head on over to the composer branch and make a suggestion there.

**Pull request closed without merging**
